# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdb3598b59cb9f698240d7853172304e603f389b7c23e91ae49f26f9a45980576dd96d6115f0e81fd186bec5baaf442daa5fe7878ebdae1e2fe1a439bdf3012e

test:
  secret_key_base: 849e1299b2ad5935edda643c23f246781f84a0373d590773baae4ba269d908d65ac67d143182b902dd779222eb0b596d4814b85c15b0870346ac574424cf712a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
